[package]
name = "localdeck"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8"
rusqlite = { version = "0.38", features = ["bundled"] }
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
chrono = { version = "0.4", features = ["clock"] }
rouille = "3"
serde_json = "1"
mime_guess = "2.0.5"
thiserror = "2.0.18"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Storage_FileSystem"] }


[dev-dependencies]
tempfile = "3"
