[package]
name = "localdeck"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.3"
rusqlite = { version = "0.38.0", features = ["bundled"] }
walkdir = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
anyhow = "1.0.100"
